### ISSUE TITLE
Error "Could not satisfy explicit device specification"

### ISSUE THREAD

**Issue by alonewithyou** [galeone/tfgo#16]
When I'm trying to import a trained tf model in tfgo, I sometimes encounter the following error. Is there any restriction between the platform of training and testing?

2019-03-05 02:43:13.272111: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: infer
2019-03-05 02:43:13.273853: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { tag }
2019-03-05 02:43:13.275663: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-05 02:43:13.282021: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-03-05 02:43:13.282044: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on this host (shining-Inspiron-5680): /proc/driver/nvidia/version does not exist
2019-03-05 02:43:13.296950: I tensorflow/cc/saved_model/loader.cc:259] SavedModel load for tags { tag }; Status: fail. Took 24847 microseconds.
panic: Cannot assign a device for operation embeddings/encoder/embedding_encoder/Initializer/random_uniform/RandomUniform: Could not satisfy explicit device specification '' because the node {{colocation_node embeddings/encoder/embedding_encoder/Initializer/random_uniform/RandomUniform}} was colocated with a group of nodes that required incompatible device '/device:GPU:0'
Colocation Debug Info:
Colocation group had the following types and devices: 
Assign: CPU 
Identity: CPU XLA_CPU XLA_GPU 
VariableV2: CPU 
Mul: CPU XLA_CPU XLA_GPU 
Add: CPU XLA_CPU XLA_GPU 
Sub: CPU XLA_CPU XLA_GPU 
GatherV2: CPU XLA_CPU XLA_GPU 
RandomUniform: CPU XLA_CPU XLA_GPU 
Const: CPU XLA_CPU XLA_GPU 

Colocation members and user-requested devices:
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/shape (Const) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/min (Const) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/max (Const) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/RandomUniform (RandomUniform) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/sub (Sub) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform/mul (Mul) 
  embeddings/encoder/embedding_encoder/Initializer/random_uniform (Add) 
  embeddings/encoder/embedding_encoder (VariableV2) /device:GPU:0
  embeddings/encoder/embedding_encoder/Assign (Assign) /device:GPU:0
  embeddings/encoder/embedding_encoder/read (Identity) /device:GPU:0
  dynamic_seq2seq/encoder/embedding_lookup/axis (Const) /device:GPU:0
  dynamic_seq2seq/encoder/embedding_lookup (GatherV2) /device:GPU:0
  save/Assign_3 (Assign) /device:GPU:0
  save_1/Assign_3 (Assign) /device:GPU:0

	 [[{{node embeddings/encoder/embedding_encoder/Initializer/random_uniform/RandomUniform}} = RandomUniform[T=DT_INT32, _class=["loc:@embeddings/encoder/embedding_encoder"], _output_shapes=[[7709,128]], dtype=DT_FLOAT, seed=0, seed2=0](embeddings/encoder/embedding_encoder/Initializer/random_uniform/shape)]]

**Comment by galeone** [comment]
The SavedModel object contains the complete graph description.
You trained your model with some node placed the device GPU:0 and saved the model with this information stored inside.
Then, when you load this model on a device without a GPU it fails (as your error states `kernel driver does not appear to be running on this host (shining-Inspiron-5680): /proc/driver/nvidia/version does not exist`).

The proper way to export a model, that will work on any device is to clear all the device placement of every node. This can be automatically solved by passing the `clear_devices=True` parameter to the `builder.add_meta_graph_and_variables` call:

```python
        builder = tf.saved_model.builder.SavedModelBuilder("export")
        builder.add_meta_graph_and_variables(sess, ["tag"], clear_devices=True)
```

Let me know if it works
